sudo: false

language: "python"

python: 3.7

install:
  - pip install pip
  - python get-poetry.py --preview -y
  - source $HOME/.poetry/env
  - poetry install -v

script:
  - poetry run pytest

notifications:
  email: false
